### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by v6** [todddeluca/python-vagrant#31]
Do you think it is possible to support Python 3? 

If you would be interested in that, I could rewrite fabric commands to use invoke. 

Invoke is another task execution and tool library written by the same author as fabric. 

https://pypi.python.org/pypi/invoke/0.9.0

**Comment by todddeluca** [comment]
I'm open to a pull request.  

I have heard that one can write a codebase that works in python 2 and 3.  I imagine such a thing could be done with python-vagrant fairly easily, but I do not have the time in the near term to do it myself.

**Comment by jdupl** [comment]
I will translate to python 2/3 compatible codebase.

**Comment by todddeluca** [comment]
Great!

**Comment by signalpillar** [comment]
Recommend the following changes to add Python 3 support #42

**Comment by ookull** [comment]
I'm using python-vagrant 0.5.8 with python 3.4.2. I added "universal_newlines=True" to subprocess.call() and after that it seems to be python3 compatible.

**Comment by signalpillar** [comment]
@ookull this is true if you don't need backward compatibility with Python 2.7 and do not run tests =)

I decided to put a little bit effort but keep it working, including tests, for both major versions of python.
Tested with 3.4.3 and 2.7.10.

**Comment by todddeluca** [comment]
Version 0.5.9 incorporates the Python 3 pull request by @signalpillar .  Enjoy!
