### ISSUE TITLE
shutoff status not supported

### ISSUE THREAD

**Issue by jmacfar** [todddeluca/python-vagrant#32]
The module throws an error when parsing something like:

build0X0Y                shutoff (libvirt)

Assigning and adding SHUTOFF to list of statuses fixes the issue. This is after running 'vagrant halt'

Is this a vagrant-libvirt specific status?

**Comment by todddeluca** [comment]
Argh!  I constrained status to only known state values for the sake of parsing.  I'm working on a fix that parses the `--machine-readable` command output, so I can lift this constraint.  That should fix this bug.

**Comment by todddeluca** [comment]
This should be fixed in version 0.5.5 which parses the --machine-readable output from Vagrant
