### ISSUE TITLE
how to configure port forwarding?

### ISSUE THREAD

**Issue by jmdcal** [todddeluca/python-vagrant#39]
How can I setup port forwarding?

**Comment by omoman** [comment]
You need to configure that in your Vagrantfile. See [this](http://docs.vagrantup.com/v2/networking/forwarded_ports.html). `python-vagrant` does not have the ability to generate a Vagrantfile with port forwarding for you at the moment.

**Comment by jmdcal** [comment]
Thank you, that is what I figured out as well..
