### ISSUE TITLE
how to change the vm name

### ISSUE THREAD

**Issue by jmdcal** [todddeluca/python-vagrant#40]
calling init creates a box with the name default, how we supposed to set the vm name ?

**Comment by omoman** [comment]
Set the `box_name` parameter.

```python
def init(self, box_name=None, box_url=None)
```

**Comment by jmdcal** [comment]
The box name is set and results to: 

config.vm.box = "cent7-1.1503"

the vagrant is creating the machine with the vm_name "default". So I want to be able to set the VMNAME not the boxname.

give the root : vagrantfiles/c7-salt-master

it creates this structure:
    vagrantfiles/c7-salt-master/.vagrant/machines/default/virtualbox/

**Comment by omoman** [comment]
In that case, you need to manually add the name configuration to your Vagrantfile, which will depend on which provider you are using. See [this](http://docs.vagrantup.com/v2/virtualbox/configuration.html) for Virtualbox. The option you are looking for is `v.name`.

There isn't a way to automatically generate a Vagrantfile using `python-vagrant` at the moment with provider configuration.

**Comment by omoman** [comment]
From the Vagrant Docs,

> You can customize the name that appears in the VirtualBox GUI by setting the `name` property. By default, Vagrant sets it to the containing folder of the Vagrantfile plus a timestamp of when the machine was created. 

So you could also simply change the name of the directory you are calling `vagrant up` in.

**Comment by jmdcal** [comment]
Ok, because on the subsequent calls to status and up etc, I can pass in the vm_name which has to be default. 
My solution is to manage multiple vagrant root dirs.

Thanks for the clarification. 
mike

**Comment by todddeluca** [comment]
Generating or modifying Vagrantfiles is not in the scope of the python-vagrant project currently.  Thanks for your comments @omoman
