### ISSUE TITLE
Specify Vagrantfile location

### ISSUE THREAD

**Issue by TuxOtaku** [todddeluca/python-vagrant#43]
How do I specify where the Vagrantfile is located?

**Comment by omoman** [comment]
You can set the `root` parameter in the Vagrant c'tor. https://github.com/todddeluca/python-vagrant/blob/master/vagrant/__init__.py#L229

**Comment by conorsch** [comment]
By way of example:

```
import vagrant
v = vagrant.Vagrant(root="path/to/project")
```

OK to close this issue.
