### ISSUE TITLE
which('vagrant') returns none

### ISSUE THREAD

**Issue by Firesphere** [todddeluca/python-vagrant#53]
As of today, the which command suddenly returns none, Vagrant 1.8.4

I have no idea what changed, yesterday it worked.

**Comment by todddeluca** [comment]
Hmm.  I installed Vagrant 1.8.4 and the python-vagrant `which` function works for me on Mac OS X 10.11.5.

```
$ python -c 'import vagrant; print vagrant.which("vagrant")'
/usr/local/bin/vagrant
```

**Comment by Firesphere** [comment]
Ok. Problem found...
Apparently, /usr/local/bin wasn't in my environment variables anymore. Strange, but fixed it. Thanks for your time!
